### ISSUE TITLE
Handling Errors / is_wp_error

### ISSUE THREAD

**Issue by kraftner** [Tarendai/WordPress-The-Right-Way#49]
At http://www.wptherightway.org/en/debugging/handlingerrors.html it says

>is_wp_error

>This is a helpful method to simplify error checking. It checks if a returned value was a WP_Error >object, **and also checks for a handful of other error values**. 

Looking at [the source](https://github.com/WordPress/WordPress/blob/4.0/wp-includes/class-wp-error.php#L247-L261) It seems that there are no other checks than for `WP_Error`.

Anything I missed or should this part of the sentence just be removed?

**Comment by Tarendai** [comment]
I don't think the bolded text should be removed, instead it should be replaced to state clearly it does not check for other values. Perhaps:

> This is a helpful method to simplify error checking. It checks if a returned value was a WP_Error >object, but does not check for other error values. It's shorthand for `if ( get_class( $variable ) == 'WP_Error' )`

**Comment by kraftner** [comment]
Even better.
