### ISSUE TITLE
Inconsistency or Misunderstood Inside the Documentation.

### ISSUE THREAD

**Issue by joaosvieira** [Tarendai/WordPress-The-Right-Way#65]
Hello, I'm currently translating this entire documentation to **Brazilian Portuguese** and I've found some inconsistency in your documentation, I'd thought about creating an *Issue Request* before, but I've been busy and I couldn't contribute to the **repo** very often :/

To be honest I am not quite sure if it's wrong or I misunderstood something. My point is that I'd like to make this *Issue Request* open for a future reference, 'til I finish with the translations. So down below I'm putting the "errors" or "misunderstoods" that I have found through out the process.

### Errors or Misunderstoods

You can find the following quote by accessing this [link](https://github.com/Tarendai/WordPress-The-Right-Way/tree/master/en/post_types#post-types), that is located in the first paragraph.

> "When you change your post types or you'll get 404s"

I couldn't understand what did you try to say by, *When you change your post types...*, then what? Or *you'll get 404s*? I'm sorry if I'm being ignorant here, but I'd very appreciate some like here. Could you explain it to me?

I already saw some "flaws" but I cannot remember where it happened right now, so during the translating process I'll be sending you some feedback right here in this *Issue Request*.

**Comment by ashmatadeen** [comment]
My understanding: 

If you make changes to your post types but don't flush the rewrite rules after the change, the permalinks affected by the post type changes will go to a 404 page instead of loading the expected content.

**Comment by Tarendai** [comment]
Most pages started out as notes that quickly mention what needs saying so that they're still useful to people, prior to writing them out in full prose.

I expect that paragraph was written out as notes, then expanded on, with that snippet remaining in its original note form, but @ashmatadeen has the right idea, changing your taxonomies and post types in code requires a rewrite rules update/flush for new URL structures to work, else you'll get 404 pages instead

**Comment by joaosvieira** [comment]
@ashmatadeen and @Tarendai Thank You! Now that I have a better understanding of the idea I can improve the translation. Cheers!
