### ISSUE TITLE
WPLANG is deprecated since 4.0

### ISSUE THREAD

**Issue by benoitchantre** [Tarendai/WordPress-The-Right-Way#71]
In chapter 11, there's a mention of the `WP_LANG`constant, but it has been [deprecated since WP 4.0](https://core.trac.wordpress.org/changeset/29630).

The language is now set in *General Settings > Site Language*

**Comment by Tarendai** [comment]
Hey, just for reference, can you specify chapters by name? Chapter 11 in English may not be chapter 11 in Japanese

**Comment by benoitchantre** [comment]
The chapter name is I18n.
Thanks for the change.
